# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found 
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn check
  deploy:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run: echo "A first hello"

  # deploy:
  #   working_directory: ~/repo
  #   docker:
  #     - image: circleci/node:8.11
  #   environment:
  #     - SOURCE_BRANCH: master
  #     - TARGET_BRANCH: gh-pages
  #     - GITHUB_EMAIL: circleci@gh-pages.com
  #     - GITHUB_NAME: CircleCI
  #   steps:
  #     - run:
  #       name: Deploy GitHub
  #       command: |
  #         if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
  #             git config --global user.email ${GITHUB_EMAIL}
  #             git config --global user.name ${GITHUB_NAME}

  #             git clone $CIRCLE_REPOSITORY_URL out
  #             cd out
  #             git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
  #             git rm -rf .
  #             cd ..

  #             yarn docs:build
  #             cp -a dest/. out/.
  #             mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.

  #             cd out
  #             git add -A
  #             git commit -m "Automated deployment to GitHub Pages ${CIRCLE_SHA1}" --allow-empty
  #             git push origin $TARGET_BRANCH
  #         fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy
          # requires:
          #   - build
          # filters:
          #   branches:
          #     only: master